### ISSUE TITLE
Issues compiling on VS 15.7.5 with MSVC++ compiler 19.14.26433.0 

### ISSUE THREAD

**Issue by thomas-frantz** [ITHare/kscope#33]
I accidentally posted this on obf and didn't realize it until this morning

When compiling I've set the ITHARE_KSCOPE_SEED and I'm getting these errors:

```
src\obf-kscope\kscope\src\kscope.h(249): error C2975: 'seed': invalid template argument for 'ithare::kscope::KscopeExtendedIntVarContext', expected compile-time constant expression
src\obf-kscope\kscope\src\kscope.h(162): note: see declaration of 'seed'
'ithare::kscope::KscopeInt<int32_t,16374999633001647152,30,0>' being compiled
src\obf-kscope\kscope\src\kscope.h(257): error C2975: 'seed': invalid template argument for 'ithare::kscope::KscopeCondInjection', expected compile-time constant expression
src\obf-kscope\kscope\src\kscope.h(228): note: see declaration of 'seed'
src\obf-kscope\kscope\src\kscope.h(485): note: see reference to class template instantiation 'ithare::kscope::KscopeInjection<T,Context,InjectionRequirements,0,30>' being compiled
        with
        [
            T=unsigned int,
            Context=ithare::kscope::ObfIntVarContext<unsigned int,0,30>,
            InjectionRequirements=ithare::kscope::KscopeInt<int32_t,16374999633001647152,30,0>::InjectionRequirements
        ]
src\obf-kscope\kscope\src\kscope.h(102): error C2975: 'seed': invalid template argument for 'ithare::kscope::kscope_random_choice_from_list', expected compile-time constant expression
src\obf-kscope\kscope\src\impl\kscope_injection.h(128): note: see declaration of 'seed'
```

Also tried using `/c++latest` and `/c++17`.

And thanks for your work on this by the way! Awesome project.

**Comment by nobugs-hare** [comment]
Did you try to "x64 Native Tools Command Prompt for VS 2017" command-line window, then go into /test/win/ (either in kscope or in obf project) and run randomtest.bat (it does set all the necessary flags in quite a few different combinations)? I just re-checked - randomtest.bat does work under VS 15.5.5 , so let's see whether it works in your environment. If randomtest.bat doesn't work for you - please post its output (and it will start to look as a likely regression in MSVC), but if it does - please take a look at valid combinations of command-line parameters in generatedrandomtest.bat (which is created after randomtest.bat is run).

**Comment by thomas-frantz** [comment]
Looks to still error with /Zi 😞 

[error-kscope-develop-Zi.log](https://github.com/ITHare/kscope/files/2193505/error-kscope-develop-Zi.log)

**Comment by nobugs-hare** [comment]
:-( . Will try to take a look at it tomorrow.

**Comment by thomas-frantz** [comment]
If you need me to do anything else, please let me know :)

**Comment by nobugs-hare** [comment]
This is indeed reproducible with 15.7.5, and at this point it looks as a regression in MSVC :-( (and at the first try, I wasn't able to find a workaround :-( ). I will try to submit a bug to MSVC team, maybe tomorrow, but nobody knows how long it will take them to fix it :-( . Meanwhile, downgrade to 15.5.5 should help (exactly the same code did work there, I double-checked it before upgrading).

**Comment by thomas-frantz** [comment]
So I got around to installing 15.8 Preview 4 this morning, and using the x64 Native Commandprompt for VS 2017 Preview, the tests in kscope-develop is now compiling and generating code again :)

So far it's running through it's tests and seems to be working.

**Comment by nobugs-hare** [comment]
Thanks a LOT! So the regression was SOOOO bad that they already ran into it and fixed it too...

I added a #warning for _MSC_VER 1913 and 1914, so that people trying to use 15.7 know about regression, and more importantly - what to do if they run into this kind of errors. Side note: my current MSVC box died exactly when  I tried to test it, but I still pushed this #warning to develop even as it is untested (this issue is way too important and #warning looks simple enough to take a risk, but please let me know if you run into any problems with these three lines I added recently; I am going to test them myself, but with a box being dead, it is going to take some time :-( ). 

Also, it is indeed very good to know that people are starting to use this thing for real-world projects, and I am ready to help in any way I can :-) (well, within reason ;-) ).

**Comment by thomas-frantz** [comment]
Yup that seems to be working :) Tried it on both 15.7.5 and 15.8 P4 and got the warning where I should. 

As for the second part, we actually got a guy on your team who backed the books on kickstarter and suggested this lib. So far we're pretty excited to try it out :) The game we're trying this on is a pretty old MMO, and we're trying to bring it up to speed and modernize it. Unfortunately it's plagued with security problems. While this library plus obf won't be the end-all-be-all of fixing that, it will go a long way in securing parts of the client while we also do other things.

Thanks for your work and efforts on this 👍

**Comment by nobugs-hare** [comment]
Thanks! If you have any further issues (after all, this whole thing is experimental) - please LMK.
